#!/usr/bin/env python3
"""
Databricks Tools OAuth Validation

Validates the Databricks App Connection (U2M) credentials used by Glean’s
Databricks tools (Genie and SQL actions in Assistant and Agents).

Runs two required checks plus two optional smoke tests:
  1. OIDC Discovery  - confirms workspace OAuth endpoints are reachable
  2. M2M Token Test  - confirms App Connection exists and secret is valid
  3. SQL Smoke Test  - (optional) runs a query against samples.tpch.orders
  4. Genie API Test  - (optional) starts a Genie conversation

Usage:
    # Required checks only
    python validate_tools_oauth.py \\
        --workspace-host https://dbc-xxxx.cloud.databricks.com \\
        --client-id YOUR_CLIENT_ID \\
        --client-secret YOUR_CLIENT_SECRET

    # With optional SQL smoke test
    python validate_tools_oauth.py \\
        --workspace-host https://dbc-xxxx.cloud.databricks.com \\
        --client-id YOUR_CLIENT_ID \\
        --client-secret YOUR_CLIENT_SECRET \\
        --warehouse-id YOUR_WAREHOUSE_ID

    # With optional Genie test
    python validate_tools_oauth.py \\
        --workspace-host https://dbc-xxxx.cloud.databricks.com \\
        --client-id YOUR_CLIENT_ID \\
        --client-secret YOUR_CLIENT_SECRET \\
        --genie-space-id YOUR_GENIE_SPACE_ID

Requirements:
    pip install requests

Important:
    A PASS on the M2M token test confirms the App Connection exists and the
    secret is correct. It does NOT prove the full U2M (browser redirect) flow
    will work. Also verify the redirect URL in your Databricks App Connection
    exactly matches the callback URL generated by Glean after saving the tool.

Recommended test dataset:
    samples.tpch is available in every Databricks workspace with no setup.
    Create a Genie space using samples.tpch.orders and samples.tpch.customer
    if you want to test the Genie API.

Questions? Ping sabrina.wang@glean.com
"""

import argparse
import json
import sys
import requests


SEP = "=" * 65


def check_oidc_discovery(workspace_host: str) -> dict:
    url = f"{workspace_host}/oidc/.well-known/oauth-authorization-server"
    print(f"\n[1] OIDC Discovery")
    print(f"    {url}")
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        config = resp.json()
        print(f"    Status : {resp.status_code} OK")
        print(f"    authorization_endpoint : {config.get('authorization_endpoint')}")
        print(f"    token_endpoint         : {config.get('token_endpoint')}")
        scopes = config.get("scopes_supported", [])
        for s in ["all-apis", "offline_access"]:
            print(f"    scope '{s}': {'found' if s in scopes else 'MISSING'}")
        print("    Result : PASS")
        return config
    except Exception as e:
        print(f"    Result : FAIL")
        print(f"    Error  : {e}")
        print("    Fix    : verify --workspace-host is correct and reachable.")
        return {}


def check_client_credentials(workspace_host: str, client_id: str, client_secret: str):
    url = f"{workspace_host}/oidc/v1/token"
    print(f"\n[2] M2M Client Credentials Test")
    print(f"    {url}")
    try:
        resp = requests.post(
            url,
            data={"grant_type": "client_credentials", "scope": "all-apis"},
            auth=(client_id, client_secret),
            timeout=10,
        )
        if resp.status_code == 200:
            data = resp.json()
            print(f"    Result     : PASS")
            print(f"    Token type : {data.get('token_type')}")
            print(f"    Expires in : {data.get('expires_in')} seconds")
            return True, data.get("access_token")
        else:
            print(f"    Result : FAIL (HTTP {resp.status_code})")
            try:
                err = resp.json()
                print(f"    error             : {err.get('error')}")
                print(f"    error_description : {err.get('error_description')}")
                desc = err.get("error_description") or ""
                if "not available in Databricks account" in desc:
                    print()
                    print("    This Client ID is not a Databricks App Connection.")
                    print("    A service principal credential passes M2M but fails for U2M.")
                    print("    Fix: go to Account Console > Settings > App Connections and")
                    print("    create a new App Connection. Use that Client ID here.")
            except Exception:
                print(f"    Raw: {resp.text[:300]}")
            return False, None
    except Exception as e:
        print(f"    Result : FAIL")
        print(f"    Error  : {e}")
        return False, None


def check_sql(workspace_host: str, access_token: str, warehouse_id: str | None) -> bool:
    headers = {"Authorization": f"Bearer {access_token}"}
    print(f"\n[3] SQL Statement API Smoke Test (optional)")

    if not warehouse_id:
        print("    No --warehouse-id provided. Discovering available warehouses...")
        wh = requests.get(f"{workspace_host}/api/2.0/sql/warehouses", headers=headers, timeout=10)
        if wh.status_code == 200:
            warehouses = wh.json().get("warehouses", [])
            if warehouses:
                running = [w for w in warehouses if w.get("state") == "RUNNING"]
                chosen = (running or warehouses)[0]
                warehouse_id = chosen["id"]
                print(f"    Using warehouse: {chosen['name']} ({warehouse_id}, {chosen.get('state')})")
            else:
                print("    [SKIP] No SQL warehouses found. Create one in SQL > SQL Warehouses.")
                return False
        else:
            print(f"    [SKIP] Could not list warehouses: HTTP {wh.status_code}")
            return False

    SQL = (
        "SELECT o_orderstatus AS status, COUNT(*) AS cnt, "
        "ROUND(SUM(o_totalprice), 2) AS total "
        "FROM samples.tpch.orders "
        "GROUP BY o_orderstatus ORDER BY total DESC LIMIT 5"
    )
    r = requests.post(
        f"{workspace_host}/api/2.0/sql/statements",
        headers=headers,
        json={"warehouse_id": warehouse_id, "statement": SQL, "wait_timeout": "30s", "disposition": "INLINE"},
        timeout=60,
    )
    if r.status_code == 200 and r.json().get("status", {}).get("state") == "SUCCEEDED":
        result = r.json()
        cols = [c["name"] for c in result["manifest"]["schema"]["columns"]]
        rows = result["result"]["data_array"]
        print("    Result : PASS")
        print(f"    {'  |  '.join(cols)}")
        for row in rows:
            print(f"    {'  |  '.join(str(v) for v in row)}")
        return True
    else:
        state = r.json().get("status", {}).get("state", "unknown") if r.status_code == 200 else f"HTTP {r.status_code}"
        print(f"    Result : FAIL ({state})")
        return False


def check_genie(workspace_host: str, access_token: str, genie_space_id: str) -> bool:
    headers = {"Authorization": f"Bearer {access_token}"}
    print(f"\n[4] Genie API Test (optional)")
    print(f"    Space ID : {genie_space_id}")
    gr = requests.post(
        f"{workspace_host}/api/2.0/genie/spaces/{genie_space_id}/start-conversation",
        headers=headers,
        json={"content": "How many total orders are there?"},
        timeout=30,
    )
    if gr.status_code == 200:
        print(f"    Result          : PASS")
        print(f"    Conversation ID : {gr.json().get('conversation_id')}")
        return True
    elif gr.status_code == 404:
        print(f"    Result : FAIL — space not found: {genie_space_id}")
        print("    Verify the space ID and that the credentials have access.")
    elif gr.status_code == 403:
        print("    Result : FAIL — permission denied.")
        print("    Grant CAN_USE on the Genie space to the App Connection service principal.")
    else:
        print(f"    Result : FAIL (HTTP {gr.status_code})")
        try:
            print(f"    {gr.json().get('message', gr.text[:300])}")
        except Exception:
            print(f"    {gr.text[:300]}")
    return False


def main():
    parser = argparse.ArgumentParser(
        description="Validate Databricks tools (U2M App Connection) OAuth credentials for Glean"
    )
    parser.add_argument("--workspace-host", required=True,
        help="Databricks workspace URL (e.g. https://dbc-xxxx.cloud.databricks.com)")
    parser.add_argument("--client-id", required=True, help="App Connection Client ID")
    parser.add_argument("--client-secret", required=True, help="App Connection Client Secret")
    parser.add_argument("--account-id", default="", help="Databricks account ID (reference only)")
    parser.add_argument("--warehouse-id", default="",
        help="SQL Warehouse ID for smoke test (auto-discovered if omitted)")
    parser.add_argument("--genie-space-id", default="",
        help="Genie Space ID for Genie API test (skipped if omitted)")
    args = parser.parse_args()

    host = args.workspace_host.rstrip("/")

    print(SEP)
    print("Databricks Tools OAuth Validation")
    print(SEP)
    print(f"Workspace Host : {host}")
    if args.account_id:
        print(f"Account ID     : {args.account_id}")
    print(f"Client ID      : {args.client_id}")

    oidc_config = check_oidc_discovery(host)
    creds_ok, access_token = check_client_credentials(host, args.client_id, args.client_secret)

    sql_ok = None
    genie_ok = None
    if creds_ok and access_token:
        sql_ok = check_sql(host, access_token, args.warehouse_id or None)
        if args.genie_space_id:
            genie_ok = check_genie(host, access_token, args.genie_space_id)
        else:
            print("\n[4] Genie API Test (optional)")
            print("    Skipped — pass --genie-space-id to enable.")
    else:
        print("\n[3] SQL Smoke Test   : Skipped (no valid token)")
        print("[4] Genie API Test   : Skipped (no valid token)")

    oidc_ok = bool(oidc_config.get("authorization_endpoint"))

    print()
    print(SEP)
    print("Summary")
    print(SEP)
    print(f"  OIDC Discovery     : {'PASS' if oidc_ok else 'FAIL'}")
    print(f"  M2M Token Test     : {'PASS' if creds_ok else 'FAIL'}")
    if sql_ok is not None:
        print(f"  SQL Smoke Test     : {'PASS' if sql_ok else 'FAIL'}")
    if genie_ok is not None:
        print(f"  Genie API Test     : {'PASS' if genie_ok else 'FAIL'}")

    if oidc_ok and creds_ok:
        print()
        print("  Glean Tools Configuration")
        print(f"    Host URL          : {host}")
        print(f"    Authorization URL : {oidc_config.get('authorization_endpoint', host + '/oidc/v1/authorize')}")
        print(f"    Token URL         : {oidc_config.get('token_endpoint', host + '/oidc/v1/token')}")
        print(f"    Scopes            : all-apis,offline_access")
        if args.warehouse_id:
            print(f"    Warehouse ID      : {args.warehouse_id}")
        if args.genie_space_id:
            print(f"    Genie Space ID    : {args.genie_space_id}")
        print()
        print("  After saving the Glean tool, copy the generated callback URL")
        print("  back into the Databricks App Connection redirect URLs field.")
    else:
        print()
        print("  One or more checks failed. See details above.")

    print(SEP)
    sys.exit(0 if (oidc_ok and creds_ok) else 1)


if __name__ == "__main__":
    main()
