# Databricks notebook source
# DBTITLE 1,Overview
# MAGIC %md
# MAGIC # Databricks Tools OAuth Validation
# MAGIC
# MAGIC Validates the OAuth configuration for **Databricks Tools in Glean** (Genie and SQL actions).
# MAGIC
# MAGIC ## What you need
# MAGIC
# MAGIC | What | Where to find it |
# MAGIC |---|---|
# MAGIC | Workspace Host URL | Databricks workspace browser bar, e.g. `https://dbc-xxxx.cloud.databricks.com` |
# MAGIC | Client ID | Account Console → Settings → App Connections |
# MAGIC | Client Secret | Copied at App Connection creation (not retrievable after) |
# MAGIC | SQL Warehouse ID | *(optional)* — auto-discovered if blank |
# MAGIC | Genie Space ID | *(optional)* — only needed to test the Genie API |
# MAGIC
# MAGIC ## What this notebook tests
# MAGIC
# MAGIC 1. **OIDC Discovery** — confirms endpoints are reachable, returns exact URLs for Glean config
# MAGIC 2. **M2M Token Test** — confirms the App Connection exists and secret is correct
# MAGIC 3. **SQL Smoke Test** *(optional)* — runs a query against `samples.tpch.orders`
# MAGIC 4. **Genie API Test** *(optional)* — starts a Genie conversation to confirm the action will work
# MAGIC
# MAGIC > **Important:** Steps 1–2 use M2M (client_credentials). A PASS is strong evidence credentials
# MAGIC > are valid, but the full Glean flow uses U2M (user OAuth with browser redirect). Also verify
# MAGIC > the redirect URL in Databricks exactly matches the callback URL generated by Glean.
# MAGIC
# MAGIC *Recommended test dataset: `samples.tpch` is available in every Databricks workspace with no setup.*
# MAGIC
# MAGIC ---
# MAGIC *Questions? Ping sabrina.wang@glean.com*

# COMMAND ----------

# DBTITLE 1,Widget Inputs
dbutils.widgets.text("WORKSPACE_HOST", "", "Workspace Host")
dbutils.widgets.text("CLIENT_ID", "", "Client ID")
dbutils.widgets.text("CLIENT_SECRET", "", "Client Secret")
dbutils.widgets.text("ACCOUNT_ID", "", "Account ID (optional)")
dbutils.widgets.text("GENIE_SPACE_ID", "", "Genie Space ID (optional)")
dbutils.widgets.text("WAREHOUSE_ID", "", "SQL Warehouse ID (optional)")

WORKSPACE_HOST = dbutils.widgets.get("WORKSPACE_HOST").rstrip("/")
CLIENT_ID      = dbutils.widgets.get("CLIENT_ID").strip()
CLIENT_SECRET  = dbutils.widgets.get("CLIENT_SECRET").strip()
ACCOUNT_ID     = dbutils.widgets.get("ACCOUNT_ID").strip()
GENIE_SPACE_ID = dbutils.widgets.get("GENIE_SPACE_ID").strip()
WAREHOUSE_ID   = dbutils.widgets.get("WAREHOUSE_ID").strip()

print("Configuration loaded:")
print(f"  Workspace Host : {WORKSPACE_HOST}")
print(f"  Account ID     : {ACCOUNT_ID or '(not set)'}")
print(f"  Client ID      : {CLIENT_ID or '(not set)'}")
print(f"  Client Secret  : {'*' * len(CLIENT_SECRET) if CLIENT_SECRET else '(not set)'}")
print(f"  Genie Space ID : {GENIE_SPACE_ID or '(not set)'}")
print(f"  Warehouse ID   : {WAREHOUSE_ID or '(not set)'}")

# COMMAND ----------

# DBTITLE 1,Step 2 - OIDC Discovery
# MAGIC %md
# MAGIC ## Step 2 — OIDC Discovery
# MAGIC
# MAGIC - `authorization_endpoint` — **Authorization URL** to enter in Glean
# MAGIC - `token_endpoint` — **Token URL** to enter in Glean
# MAGIC - Confirm `all-apis` and `offline_access` are in `scopes_supported`

# COMMAND ----------

import requests
import json

OIDC_DISCOVERY_URL = f"{WORKSPACE_HOST}/oidc/.well-known/oauth-authorization-server"

try:
    resp = requests.get(OIDC_DISCOVERY_URL, timeout=10)
    resp.raise_for_status()
    oidc_config = resp.json()
    print(f"[PASS] OIDC discovery reachable (HTTP {resp.status_code})")
    print(f"  authorization_endpoint : {oidc_config.get('authorization_endpoint')}")
    print(f"  token_endpoint         : {oidc_config.get('token_endpoint')}")
    scopes = oidc_config.get('scopes_supported', [])
    for s in ['all-apis', 'offline_access']:
        print(f"  scope '{s}': {'found' if s in scopes else 'MISSING'}")
except Exception as e:
    oidc_config = {}
    print(f"[FAIL] {e}")
    print("  Fix: verify WORKSPACE_HOST is correct and reachable.")

# COMMAND ----------

# DBTITLE 1,Step 3 - M2M Token Test
# MAGIC %md
# MAGIC ## Step 3 — M2M Client Credentials Test
# MAGIC
# MAGIC **PASS:** App Connection exists in the Databricks account and the Client Secret is correct.
# MAGIC
# MAGIC **PASS does NOT prove** the full U2M flow works. Also verify:
# MAGIC - Redirect URL in the App Connection exactly matches the Glean callback URL
# MAGIC - `offline_access` scope is enabled on the App Connection
# MAGIC
# MAGIC **Common failures:**
# MAGIC - `invalid_client` — wrong Client ID or Secret
# MAGIC - `OAuth application ... not available in Databricks account` — the Client ID is a
# MAGIC   service principal credential, not an App Connection. Create one under
# MAGIC   Account Console → Settings → App Connections.

# COMMAND ----------

TOKEN_URL = f"{WORKSPACE_HOST}/oidc/v1/token"

if not CLIENT_ID or not CLIENT_SECRET:
    print("[SKIP] CLIENT_ID or CLIENT_SECRET not set.")
else:
    try:
        token_resp = requests.post(
            TOKEN_URL,
            data={"grant_type": "client_credentials", "scope": "all-apis"},
            auth=(CLIENT_ID, CLIENT_SECRET),
            timeout=10,
        )
        if token_resp.status_code == 200:
            token_data = token_resp.json()
            print("[PASS] Client credentials are valid.")
            print(f"  Token type : {token_data.get('token_type')}")
            print(f"  Expires in : {token_data.get('expires_in')} seconds")
        else:
            print(f"[FAIL] HTTP {token_resp.status_code}")
            try:
                err = token_resp.json()
                print(f"  error             : {err.get('error')}")
                print(f"  error_description : {err.get('error_description')}")
            except Exception:
                print(f"  Raw: {token_resp.text[:300]}")
    except Exception as e:
        token_resp = None
        print(f"[FAIL] {e}")

# COMMAND ----------

# DBTITLE 1,Step 4 - Summary
# MAGIC %md
# MAGIC ## Step 4 — Summary and Glean Configuration Values

# COMMAND ----------

oidc_ok  = bool(oidc_config.get("authorization_endpoint"))
creds_ok = 'token_resp' in dir() and token_resp is not None and token_resp.status_code == 200

SEP = "=" * 65
print(SEP)
print("Databricks Tools OAuth Validation Summary")
print(SEP)
print(f"\nWorkspace Host : {WORKSPACE_HOST}")
print(f"Account ID     : {ACCOUNT_ID or '(not set)'}")
print(f"Client ID      : {CLIENT_ID or '(not set)'}")
print(f"\nCheck 1 - OIDC Discovery : {'PASS' if oidc_ok else 'FAIL'}")
if oidc_ok:
    print(f"  authorization_endpoint : {oidc_config.get('authorization_endpoint')}")
    print(f"  token_endpoint         : {oidc_config.get('token_endpoint')}")
print(f"\nCheck 2 - M2M Token Test : {'PASS' if creds_ok else 'FAIL'}")
if not creds_ok and CLIENT_ID and CLIENT_SECRET:
    try:
        err = token_resp.json()
        print(f"  {err.get('error')}: {err.get('error_description')}")
        if "not available in Databricks account" in (err.get('error_description') or ''):
            print("  Fix: Client ID is not an App Connection. Go to Account Console > Settings > App Connections.")
    except Exception:
        pass
print()
print(SEP)
print("Glean Tools Configuration")
print(SEP)
print(f"  Host URL          : {WORKSPACE_HOST}")
print(f"  Authorization URL : {oidc_config.get('authorization_endpoint', WORKSPACE_HOST + '/oidc/v1/authorize')}")
print(f"  Token URL         : {oidc_config.get('token_endpoint', WORKSPACE_HOST + '/oidc/v1/token')}")
print(f"  Scopes            : all-apis,offline_access")
if GENIE_SPACE_ID:
    print(f"  Genie Space ID    : {GENIE_SPACE_ID}")
if WAREHOUSE_ID:
    print(f"  Warehouse ID      : {WAREHOUSE_ID}")
print()
print("After saving the Glean tool, copy the generated callback URL")
print("back into the Databricks App Connection redirect URLs field.")
print(SEP)
print("\nQuestions? Ping sabrina.wang@glean.com")

# COMMAND ----------

# DBTITLE 1,Step 5 (Optional) - SQL Smoke Test
# MAGIC %md
# MAGIC ## Step 5 (Optional) — SQL Statement API Smoke Test
# MAGIC
# MAGIC Runs a query against `samples.tpch.orders` — available in every Databricks workspace with no setup.
# MAGIC Auto-discovers a running warehouse if `WAREHOUSE_ID` is blank.

# COMMAND ----------

import time

if not creds_ok:
    print("[SKIP] Token test failed — cannot run smoke test.")
else:
    access_token = token_data["access_token"]
    headers = {"Authorization": f"Bearer {access_token}"}
    warehouse_id = WAREHOUSE_ID
    if not warehouse_id:
        print("No WAREHOUSE_ID provided — discovering warehouses...")
        wh = requests.get(f"{WORKSPACE_HOST}/api/2.0/sql/warehouses", headers=headers, timeout=10)
        if wh.status_code == 200:
            warehouses = wh.json().get("warehouses", [])
            if warehouses:
                running = [w for w in warehouses if w.get("state") == "RUNNING"]
                chosen = (running or warehouses)[0]
                warehouse_id = chosen["id"]
                print(f"Using warehouse: {chosen['name']} ({warehouse_id}, {chosen.get('state')})")
            else:
                print("[SKIP] No SQL warehouses found.")
        else:
            print(f"[FAIL] Could not list warehouses: HTTP {wh.status_code}")

# COMMAND ----------

SQL = "SELECT o_orderstatus AS status, COUNT(*) AS cnt, ROUND(SUM(o_totalprice),2) AS total FROM samples.tpch.orders GROUP BY o_orderstatus ORDER BY total DESC LIMIT 5"

if not creds_ok or not warehouse_id:
    print("[SKIP]")
else:
    r = requests.post(f"{WORKSPACE_HOST}/api/2.0/sql/statements",
        headers=headers,
        json={"warehouse_id": warehouse_id, "statement": SQL, "wait_timeout": "30s", "disposition": "INLINE"},
        timeout=60)
    if r.status_code == 200 and r.json().get("status", {}).get("state") == "SUCCEEDED":
        result = r.json()
        cols = [c["name"] for c in result["manifest"]["schema"]["columns"]]
        rows = result["result"]["data_array"]
        print("[PASS] SQL Statement API test succeeded!")
        print("  " + "  |  ".join(cols))
        for row in rows:
            print("  " + "  |  ".join(str(v) for v in row))
    else:
        print(f"[FAIL] HTTP {r.status_code}: {r.text[:300]}")

# COMMAND ----------

# DBTITLE 1,Step 6 (Optional) - Genie API Test
# MAGIC %md
# MAGIC ## Step 6 (Optional) — Genie API Test
# MAGIC
# MAGIC Tests the Genie API if a `GENIE_SPACE_ID` is provided.
# MAGIC
# MAGIC **To create a test Genie space:** Workspace → + New → Genie space → add `samples.tpch.orders` and `samples.tpch.customer`.

# COMMAND ----------

GENIE_TEST_QUESTION = "How many total orders are there?"

if not GENIE_SPACE_ID:
    print("[SKIP] No GENIE_SPACE_ID. Add samples.tpch tables to a Genie space, paste the ID above.")
elif not creds_ok:
    print("[SKIP] No valid token.")
else:
    gr = requests.post(f"{WORKSPACE_HOST}/api/2.0/genie/spaces/{GENIE_SPACE_ID}/start-conversation",
        headers=headers, json={"content": GENIE_TEST_QUESTION}, timeout=30)
    if gr.status_code == 200:
        print("[PASS] Genie API responded!")
        print(f"  Conversation ID : {gr.json().get('conversation_id')}")
    elif gr.status_code == 404:
        print(f"[FAIL] Genie space not found: {GENIE_SPACE_ID}")
    elif gr.status_code == 403:
        print("[FAIL] Permission denied. Grant CAN_USE on the Genie space to the service principal.")
    else:
        print(f"[FAIL] HTTP {gr.status_code}: {gr.text[:300]}")

# COMMAND ----------

# DBTITLE 1,Step 7 - Recommended Glean Test Queries
# MAGIC %md
# MAGIC ## Step 7 — Recommended Test Queries for Glean
# MAGIC
# MAGIC Use these after completing configuration in Glean. All use `samples.tpch` — no setup required.
# MAGIC
# MAGIC ### Genie (natural language in Assistant or Agent)
# MAGIC
# MAGIC - "How many orders are there?"
# MAGIC - "What are the top 5 countries by total order value?"
# MAGIC - "Show me orders with status cancelled"
# MAGIC - "What is the average order value by customer market segment?"
# MAGIC - "Which month had the highest total sales in 1995?"
# MAGIC
# MAGIC ### SQL action (Agent Builder)
# MAGIC
# MAGIC ```sql
# MAGIC SELECT COUNT(*) AS total_orders FROM samples.tpch.orders
# MAGIC ```
# MAGIC
# MAGIC ```sql
# MAGIC SELECT o_orderstatus, COUNT(*) AS cnt, ROUND(SUM(o_totalprice), 2) AS total
# MAGIC FROM samples.tpch.orders GROUP BY o_orderstatus ORDER BY total DESC
# MAGIC ```
# MAGIC
# MAGIC ```sql
# MAGIC SELECT c.c_mktsegment, COUNT(*) AS orders, ROUND(AVG(o.o_totalprice), 2) AS avg_value
# MAGIC FROM samples.tpch.orders o
# MAGIC JOIN samples.tpch.customer c ON o.o_custkey = c.c_custkey
# MAGIC GROUP BY c.c_mktsegment ORDER BY orders DESC
# MAGIC ```
